FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir dbt-duckdb==1.8.1
WORKDIR /app
COPY elt /app


CMD ["dbt", "run"]
