FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir duckdb==1.4.2 dbt-duckdb==1.8.1

WORKDIR /app
COPY elt /app
COPY raw_data /app/raw_data

CMD ["dbt", "build", "--project-dir", "/app/elt", "--profiles-dir", "/app/elt/.dbt", "--target", "dev"]
