version: 2

models:

  - name: docs_for_rag
    description: "Semantic RAG-ready dataset joining policies with support tickets."

    columns:
      - name: doc_id
        data_tests:
          - not_null:
              arguments:
                severity: warn
          - relationships:
              arguments:
                severity: warn
                column_name: doc_id
                to: ref('stg_documents')
                field: doc_id

      - name: ticket_id
        data_tests:
          - relationships:
              arguments:
                severity: warn
                column_name: ticket_id
                to: ref('stg_tickets')
                field: ticket_id

      - name: rag_chunk
        data_tests:
          - not_null:
              arguments:
                severity: warn

      - name: document_text
        data_tests:
          - not_null:
              arguments:
                severity: warn
